version: 1
directus: 10.1.0
vendor: postgres
collections:
  - collection: links
    meta:
      accountability: all
      archive_app_filter: true
      archive_field: status
      archive_value: archived
      collapse: open
      collection: links
      color: null
      display_template: null
      group: null
      hidden: false
      icon: null
      item_duplication_fields: null
      note: null
      singleton: false
      sort: null
      sort_field: null
      translations: null
      unarchive_value: draft
    schema:
      name: links
fields:
  - collection: links
    field: date
    type: date
    meta:
      collection: links
      conditions: null
      display: null
      display_options: null
      field: date
      group: null
      hidden: false
      interface: datetime
      note: null
      options: null
      readonly: false
      required: true
      sort: 4
      special: null
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: date
      table: links
      data_type: date
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: links
    field: id
    type: uuid
    meta:
      collection: links
      conditions: null
      display: null
      display_options: null
      field: id
      group: null
      hidden: true
      interface: input
      note: null
      options: null
      readonly: true
      required: false
      sort: 1
      special:
        - uuid
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: id
      table: links
      data_type: uuid
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: false
      is_unique: true
      is_primary_key: true
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: links
    field: link
    type: string
    meta:
      collection: links
      conditions: null
      display: null
      display_options: null
      field: link
      group: null
      hidden: false
      interface: input
      note: null
      options:
        iconLeft: link
        placeholder: link
      readonly: false
      required: true
      sort: 3
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: link
      table: links
      data_type: character varying
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: links
    field: name
    type: string
    meta:
      collection: links
      conditions: null
      display: null
      display_options: null
      field: name
      group: null
      hidden: false
      interface: input
      note: null
      options:
        placeholder: name
      readonly: false
      required: true
      sort: 2
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: name
      table: links
      data_type: character varying
      default_value: null
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
  - collection: links
    field: status
    type: string
    meta:
      collection: links
      conditions: null
      display: labels
      display_options:
        choices:
          - text: Hidden
            value: hidden
            background: '#292929'
          - text: Visible
            value: visible
            background: '#00FF00'
        showAsDot: true
      field: status
      group: null
      hidden: false
      interface: select-dropdown
      note: null
      options:
        choices:
          - text: Hidden
            value: hidden
          - text: Visible
            value: visible
      readonly: false
      required: false
      sort: 5
      special: null
      translations: null
      validation: null
      validation_message: null
      width: half
    schema:
      name: status
      table: links
      data_type: character varying
      default_value: hidden
      max_length: 255
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
relations: []
